### ISSUE TITLE
iPhone

### ISSUE THREAD

**Issue by Filoz** [gabrieltomescu/bootstrap-responsive-tabs#1]
Hi, I'm trying your demo on IPhone 5s, this is what I get:
![image](https://cloud.githubusercontent.com/assets/5341996/4661170/5d27b9b6-5520-11e4-8b59-65ab1cf1fc07.jpg)
is it correct?

Another thing I noticed is that when I open the list of hidden tabs, if I try to scroll down the list with my finger (using touch), if my finger is in the right part of the list, the page scroll instead of the list

Bye

**Comment by gabrieltomescu** [comment]
Hi @Filoz sorry for the late reply. This is definitely not the correct behaviour. I'll try to fix the issue over the weekend.

Stay tuned.

**Comment by gabrieltomescu** [comment]
Hi @Filoz, the issue should be fixed. Take a look.
