### ISSUE TITLE
Some features that might be useful

### ISSUE THREAD

**Issue by ThisNoName** [gabrieltomescu/bootstrap-responsive-tabs#3]
Thanks for the wonderful job.  I'm considering using this in place of regular responsive navigation.  

One feature that might help, on small screen, the option to show only the active tab, or no tab at all.  Because I would need most of the tab space for status, toolbar icon, etc.

**Comment by gabrieltomescu** [comment]
Hey @whoever123, take a look now. On screens smaller than 480px, you'll likely only see the active tab, plus the dropdown menu.
